name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  dbt_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-core dbt-bigquery

      - name: Create profiles.yml
        run: echo "${{ secrets.PROFILES_YML }}" > profiles.yml

      - name: Install dbt dependencies
        run: dbt deps

      - name: Run dbt build
        run: dbt build --profiles-dir .
