name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  dbt_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-core dbt-bigquery

      - name: Create profiles.yml with injected keyfile
        run: |
          echo "my_first_dbt_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: bubbly-granite-456918-p0
      dataset: FIL_ROUGE
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive
      keyfile_json: '${{ secrets.GCP_KEYFILE_JSON }}'
" > profiles.yml

      - name: Test dbt connection
        run: dbt debug --profiles-dir . --profile my_first_dbt_project

      - name: Run dbt build
        run: dbt build --profiles-dir . --profile my_first_dbt_project

