name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  dbt_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-core dbt-bigquery

      - name: Create profiles.yml from secret
        run: echo "${{ secrets.PROFILES_YML }}" > profiles.yml

      - name: Debug profile
        run: cat profiles.yml

      - name: Run dbt debug
        run: dbt debug --profiles-dir . --profile my_first_dbt_project

      - name: Run dbt build
        run: dbt build --profiles-dir . --profile my_first_dbt_project
