name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  dbt_ci:
    runs-on: ubuntu-latest
    env:
      GCP_KEYFILE_JSON: ${{ secrets.GCP_KEYFILE_JSON }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dbt
        run: pip install "dbt-bigquery~=1.9"

      # 1) Écrire la clé dans un fichier
      - name: Write keyfile.json
        run: |
          echo "$GCP_KEYFILE_JSON" > /tmp/keyfile.json
          # on peut vérifier que le JSON est valide
          python - <<'PY'
          import json, pathlib, sys
          p = pathlib.Path("/tmp/keyfile.json")
          try:
              json.load(p.open())
              print("✅ keyfile.json valid")
          except json.JSONDecodeError as e:
              print("❌ keyfile.json invalid:", e)
              sys.exit(1)
          PY

      # 2) Créer le profiles.yml qui pointe vers ce fichier
      - name: Write dbt profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<'YAML'
          my_first_dbt_project:
            target: dev
            outputs:
              dev:
                type: bigquery
                method: service-account       # ← on repasse en mode fichier
                project: bubbly-granite-456918-p0
                dataset: FIL_ROUGE
                threads: 4
                keyfile: /tmp/keyfile.json    # ← chemin absolu
          YAML

      - name: dbt debug
        run: dbt debug --profile my_first_dbt_project

      - name: dbt build
        run: dbt build --profile my_first_dbt_project

