name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  dbt_ci:
    runs-on: ubuntu-latest
    env:
      # Seul secret requis
      GCP_KEYFILE_JSON: ${{ secrets.GCP_KEYFILE_JSON }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install "dbt-bigquery~=1.9"

      - name: Write dbt profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<'YAML'
          my_first_dbt_project:
            target: dev
            outputs:
              dev:
                type: bigquery
                method: service-account-json       # ← IMPORTANT
                project: bubbly-granite-456918-p0  # ← en clair
                dataset: FIL_ROUGE                 # ← en clair
                threads: 4
                keyfile_json: "{{ env_var('GCP_KEYFILE_JSON') }}"
          YAML

      - name: dbt debug
        run: dbt debug --profile my_first_dbt_project

      - name: dbt build
        run: dbt build --profile my_first_dbt_project

